server:
    port: 9000

logging:
    level:
        ##org.springframework.jdbc.core: TRACE
        org.springframework.security: TRACE

spring:
    application:
        name: Auth-Server


    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://127.0.0.1:9000

    datasource:
        url: jdbc:postgresql://localhost:5432/authserver
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

jwt:
    key:
        public: classpath:app.pub
        private: classpath:app.key
        id: auth-server